# SELECT ID, LENGTH
# FROM FISH_INFO
# ORDER BY LENGTH DESC, ID ASC
# LIMIT 10;


SELECT ID, LENGTH
FROM (
    SELECT ID, LENGTH,
           RANK() OVER (ORDER BY LENGTH DESC, ID ASC) AS rnk
    FROM FISH_INFO
) AS ranked
WHERE rnk <= 10;