# SELECT CONCAT(LENGTH,'cm') AS MAX_LENGTH
# FROM FISH_INFO
# WHERE LENGTH = ( SELECT MAX(LENGTH) FROM FISH_INFO WHERE LENGTH IS NOT NULL)
# LIMIT 1;
SELECT CONCAT(MAX(LENGTH),'cm') AS MAX_LENGTH
FROM FISH_INFO