SELECT ROUTE,
       CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, 
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
-- 문자열은 정렬이 아닌 숫자로 제한
ORDER BY SUM(D_BETWEEN_DIST) DESC;
