SELECT CAR_TYPE, COUNT(*)
FROM CAR_RENTAL_COMPANY_CAR
WHERE (
      CASE WHEN OPTIONS LIKE '%통풍시트%' THEN 1 ELSE 0 END +
      CASE WHEN OPTIONS LIKE '%열선시트%' THEN 1 ELSE 0 END +
      CASE WHEN OPTIONS LIKE '%가죽시트%' THEN 1 ELSE 0 END
      ) >= 1
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;