SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# SELECT *
FROM DEVELOPERS AS D
INNER JOIN SKILLCODES AS S
ON D.SKILL_CODE & S.CODE !=0
WHERE CATEGORY = 'Front End'
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID ASC;