# SELECT ID, FISH_NAME, LENGTH
# SELECT *
# FROM FISH_INFO AS Ori
# INNER JOIN (SELECT I.FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH, N.FISH_NAME
#            FROM FISH_INFO AS I
#            INNER JOIN FISH_NAME_INFO AS N
#            ON I.FISH_TYPE = N.FISH_TYPE
#            GROUP BY I.FISH_TYPE, N.FISH_NAME) AS Sub
# ON Sub.FISH_TYPE = Ori.FISH_TYPE and Sub.MAX_LENGTH = Ori.LENGTH


-- SELECT ID, FISH_NAME, LEGNTH
# SELECT * 
# FROM FISH_INFO AS I
# INNER JOIN FISH_NAME_INFO AS N
# ON I.FISH_TYPE = N.FISH_TYPE
# WHERE ID IN (SELECT MAX(LENGTH)
#              FROM FISH_INFO AS I
#              INNER JOIN FISH_NAME_INFO AS N
#              ON I.FISH_TYPE = N.FISH_TYPE
#              GROUP BY FISH_NAME, N.FISH_TYPE)

-- SELECT ID, FISH_NAME, LEGNTH
# SELECT ID, N.FISH_NAME, I.LEGNTH
# FROM FISH_INFO AS I
# INNER JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
# INNER JOIN (SELECT FISH_NAME, MAX(LENGTH) AS MAX_LENGTH, I.FISH_TYPE
#            FROM FISH_INFO AS I
#            INNER JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
#            GROUP BY FISH_NAME, I.FISH_TYPE
#            ) AS Sub
# ON Sub.FISH_TYPE = I.FISH_TYPE
# GROUP BY FISH_NAME, MAX_LENGTH

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
INNER JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
ORDER BY I.ID;







