SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS Ori
INNER JOIN (SELECT I.FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH, N.FISH_NAME
           FROM FISH_INFO AS I
           INNER JOIN FISH_NAME_INFO AS N
           ON I.FISH_TYPE = N.FISH_TYPE
           GROUP BY I.FISH_TYPE, N.FISH_NAME) AS Sub
ON Sub.FISH_TYPE = Ori.FISH_TYPE and Sub.MAX_LENGTH = Ori.LENGTH