SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
WHERE YEAR = 2022
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING SUM(SCORE) = (SELECT MAX(TOTAL_SCORE)
                    FROM (
                        SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
                        FROM HR_GRADE 
                        WHERE YEAR = 2022
                        GROUP BY EMP_NO) AS sub1
                    );
